name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY1 }}
          port: 22
          command_timeout: 30m
          script_stop: true  # This ensures the job stops if a command fails
          script: |
            cd ~/flask-app
            
            # Update code
            git fetch origin
            git reset --hard origin/${{ github.ref_name }}

            # Kill old app instance
            pkill -f "app.py" || true

            # Start App based on branch
            if [ "${{ github.ref_name }}" == "dev" ]; then
              APP_ENV=dev APP_PORT=4000 nohup /usr/bin/python3 app.py > dev.log 2>&1 &
            fi

            if [ "${{ github.ref_name }}" == "main" ]; then
              APP_ENV=live APP_PORT=5000 nohup /usr/bin/python3 app.py > live.log 2>&1 &
            fi
            
            # Wait a moment for the process to bind to the port
            sleep 3
            echo "Deployment successful for ${{ github.ref_name }}"
            
            # Force a clean exit to prevent Signal 143/Timeout
            exit 0
